name: "publish"
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: install dependenies
      run: yarn install

    - name: build
      run: yarn build

    - name: zip
      run: |
        sudo apt install zip -y
        cd ./dist/
        npm i
        rm package-lock.json
        zip -r ../LLOneBot.zip ./* 
    
    - name: publish
      uses: ncipollo/release-action@v1
      with:
        artifacts: "LLOneBot.zip"
        draft: true
        token: ${{ secrets.RELEASE_TOKEN }}
